version: "3.9"
services:

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
      - kafka1
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="kafka-secret";'

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOO_ENABLE_AUTH: "yes"
      ZOO_SERVER_USERS: "zoo-server"
      ZOO_SERVER_PASSWORDS: "zk-server-secret"
      ZOO_CLIENT_USER: "zoo-client"
      ZOO_CLIENT_PASSWORD: "zk-client-secret"

  kafka1:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_PROTOCOL: SASL
      KAFKA_ZOOKEEPER_USER: "zoo-server"
      KAFKA_ZOOKEEPER_PASSWORD: "zk-server-secret"
      KAFKA_CFG_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      ALLOW_PLAINTEXT_LISTENER: "no"
      KAFKA_CLIENT_USER: "kafka"
      KAFKA_CLIENT_PASSWORD: "kafka-secret"
      KAFKA_INTER_BROKER_USER: "kafka"
      KAFKA_INTER_BROKER_PASSWORD: "kafka-secret"

  kafka2:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_PROTOCOL: SASL
      KAFKA_ZOOKEEPER_USER: "zoo-server"
      KAFKA_ZOOKEEPER_PASSWORD: "zk-server-secret"
      KAFKA_CFG_LISTENERS: INTERNAL://:29092,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka2:29092,EXTERNAL://localhost:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      ALLOW_PLAINTEXT_LISTENER: "no"
      KAFKA_CLIENT_USER: "kafka"
      KAFKA_CLIENT_PASSWORD: "kafka-secret"
      KAFKA_INTER_BROKER_USER: "kafka"
      KAFKA_INTER_BROKER_PASSWORD: "kafka-secret"

  kafka3:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_PROTOCOL: SASL
      KAFKA_ZOOKEEPER_USER: "zoo-server"
      KAFKA_ZOOKEEPER_PASSWORD: "zk-server-secret"
      KAFKA_CFG_LISTENERS: INTERNAL://:29092,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka3:29092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      ALLOW_PLAINTEXT_LISTENER: "no"
      KAFKA_CLIENT_USER: "kafka"
      KAFKA_CLIENT_PASSWORD: "kafka-secret"
      KAFKA_INTER_BROKER_USER: "kafka"
      KAFKA_INTER_BROKER_PASSWORD: "kafka-secret"

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "database"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  app:
    image: golang:1.17
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - mysql
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: ["go", "run", "main.go"]
    environment:
      MYSQL_DSN: "user:password@tcp(mysql:3306)/database"
      KAFKA_BROKERS: kafka1:29092,kafka2:29093,kafka3:29094
      KAFKA_USERNAME: "kafka"
      KAFKA_PASSWORD: "kafka-secret"
    profiles:
      - app

  app_test:
    image: golang:1.17
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - mysql
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: ["go", "test", "produce-subscription-change/...", "-v", "-cover"]
    environment:
      MYSQL_DSN: "user:password@tcp(mysql:3306)/database"
      KAFKA_BROKERS: kafka1:29092,kafka2:29093,kafka3:29094
      KAFKA_USERNAME: "kafka"
      KAFKA_PASSWORD: "kafka-secret"
    profiles:
      - app_test
